apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: customer
  labels:
    app: packersmovers
spec:
  replicas: 5
  minReadySeconds: 10
  selector:
    matchLabels:
      app: packersmovers
  template:
    metadata:
      labels:
        app: packersmovers
    spec:
      containers:
      - name: customer
        image: 590183902189.dkr.ecr.us-east-2.amazonaws.com/customer:1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
